spring.application.name=offer-system
spring.datasource.url=jdbc:postgresql://localhost:5434/offer_db
spring.datasource.username=postgres
spring.datasource.password=${DB_PASSWORD_PROJE1}
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=savuranmuyesseraylin@gmail.com
spring.mail.password=${GMAIL_APP_CODE}
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.smtp.starttls.required=true
